export const SOURCE_PRESETS=[
  {id:'fdic_failures',name:'FDIC BankFind — Failures & Assistance',tier:'A',kind:'json',integration:'direct_api',category:'bank_failure',official:true,refresh:'event-driven',url:'https://api.fdic.gov/banks/failures?limit=1000&format=json',rows_path:'data',note:'Bank failures/assistance and resolution attributes. Primary-source verification and outcome/provenance enrichment.'},
  {id:'fdic_financials',name:'FDIC BankFind — Financials',tier:'A',kind:'fdic_financials',integration:'episode_cert_connector',category:'bank_balance_sheet',official:true,refresh:'quarterly',url:'https://api.fdic.gov/banks/financials',rows_path:'data',note:'CERT-linked quarterly institution financials since 1992. The connector collects episode year-1 through episode year and stores deposit dynamics as verification covariates; it never overwrites peak_outflow automatically.'},
  {id:'fdic_sod',name:'FDIC BankFind — Summary of Deposits',tier:'A',kind:'fdic_sod',integration:'episode_cert_connector',category:'deposit_concentration',official:true,refresh:'annual',url:'https://api.fdic.gov/banks/sod',rows_path:'data',note:'Annual branch deposits since 1994. CERT-linked collection plus state-market HHI verification. SOD HHI is stored as a separate validation covariate and does not silently replace thesis concentration C.'},
  {id:'bis_cpmi',name:'BIS CPMI Red Book — Retail Payments',tier:'A',kind:'official_connector',integration:'direct_sdmx',category:'digital_payments',official:true,refresh:'annual',url:'https://data.bis.org/bulkdownload',rows_path:'',note:'Cashless payments, cash withdrawals/deposits, cards and payment institutions for 27 CPMI jurisdictions. Select CPMI CSV/SDMX series before scheduled ingestion.'},
  {id:'bis_fmi',name:'BIS CPMI — Financial Market Infrastructures',tier:'A',kind:'csv',integration:'bulk_config',category:'payment_infrastructure',official:true,refresh:'annual',url:'https://data.bis.org/topics/CPMI_FMI',rows_path:'',note:'Participation and activity in LVPS/RPS/FPS, CCPs/CSDs and other infrastructures; useful as payment-system capacity/resilience context.'},
  {id:'bis_credit_gap',name:'BIS Credit-to-GDP Gaps',tier:'A',kind:'csv',integration:'bulk_config',category:'macroprudential_stress',official:true,refresh:'quarterly',url:'https://data.bis.org/bulkdownload',rows_path:'',note:'Macroprudential stress/context variable for excessive credit and banking distress; scenario covariate, not a direct FP/FN cost.'},
  {id:'ecb_supervisory',name:'ECB Supervisory Banking Statistics / SDMX API',tier:'A',kind:'official_connector',integration:'direct_sdmx',category:'bank_resilience',official:true,refresh:'quarterly',url:'https://data-api.ecb.europa.eu/service/data/',rows_path:'',note:'Balance sheet, capital, asset quality, funding and liquidity. Configure SUP dataflow/key before enabling.'},
  {id:'bok_ecos',name:'한국은행 ECOS · 본원통화 102Y004/ABA1',tier:'A',kind:'official_connector',integration:'dedicated_connector',category:'korea_payments_macro',official:true,refresh:'monthly',url:'https://ecos.bok.or.kr/',rows_path:'StatisticSearch.row',note:'본원통화 구성내역(평잔, 계절조정계열) 월간 시계열. STAT_CODE 102Y004, ITEM_CODE ABA1. 거시환경 calibration용이며 지급결제 FN/FP ground truth가 아님.'},
  {id:'openfiscal',name:'열린재정 OPFI156 · 재정수입구조',tier:'A',kind:'official_connector',integration:'dedicated_connector',category:'public_fiscal_context',official:true,refresh:'annual',url:'https://openapi.openfiscaldata.go.kr/OPFI156',rows_path:'/OPFI156/row',note:'회계연도별 예산·기금·회계·세목별 총수입 구조. CONTEXTUAL_PUBLIC_PAYMENT 근거이며 지급정지/부정수급 결과 라벨이 아님.'},
  {id:'bojo_openapi',name:'보조금통합포털(e나라도움) Open API',tier:'A',kind:'official_connector',integration:'case_b_config_required',category:'subsidy_execution',official:true,refresh:'varies',url:'https://www.bojo.go.kr/ga/retrieveOpnApi.do',rows_path:'',note:'국고보조금 예산·사업·사업자 현황을 XML/JSON으로 제공. 제2사례 기반자료로 유용하나 공개 API만으로 개별 부정수급/지급정지 정답 라벨을 확보할 수 있다고 가정하면 안 됨.'},
  {id:'imf_fas',name:'IMF Financial Access Survey (FAS)',tier:'A',kind:'json',integration:'series_config',category:'financial_access',official:true,refresh:'annual',url:'https://data.imf.org/Datasets/FAS',rows_path:'',note:'Financial-service access and usage. Inclusion/external-validity covariates; configure desired series/country selection.'},
  {id:'worldbank_findex',name:'World Bank Global Findex 2025',tier:'A',kind:'csv',integration:'file_or_series_config',category:'digital_adoption_inclusion',official:true,refresh:'multi-year',url:'https://www.worldbank.org/en/publication/globalfindex/download-data',rows_path:'',note:'Cross-country digital payment/account/inclusion indicators. Strong for external validity, not for high-frequency crisis monitoring.'}
];
